- name: Disable friewall
  yum: name={{ item }} state=absent
  with_items:
    - firewalld
    - python-firewall
    - firewalld-filesystem

- name: Disable SElinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: SElinux Closed
  shell: "setenforce 0"
  failed_when: false

- name: backup default repo
  copy:
    src: /etc/yum.repos.d/CentOS-Base.repo
    dest: /etc/yum.repos.d/CentOS-Base.repo.backup

- name: get aliyun base-repo
  get_url:
    url: http://mirrors.aliyun.com/repo/Centos-7.repo
    dest: /etc/yum.repos.d/CentOS-Base.repo

- name: add aliyun epel
  get_url:
    url: http://mirrors.aliyun.com/repo/epel-7.repo
    dest: /etc/yum.repos.d/epel.repo

- name: yum clean and makecache
  shell: "yum clean all && yum makecache"

- name: install somes packages
  yum: name={{ item }}  state=latest
  with_items:
  - psmisc              # 安装psmisc 才能使用命令killall，它在keepalive的监测脚本中使用到
  - jq                  # 轻量JSON处理程序，安装docker查询镜像需要
  - socat               # 用于port forwarding
  - rsync               # 同步cluster ca 等
  - lrzsz				# sz,rz 
  - ipset				# iptables 伴随工具,使ipset持久化
  - ipvsadm             # 推荐使用ipvs 
  - nfs-utils           # {可选}挂载nfs 共享文件需要 (创建基于 nfs的PV 需要)
  - openssh-clients     

- name: Disable swap
  shell: "swapoff -a && sysctl -w vm.swappiness=0"
  ignore_errors: true

- name: Delete swap config
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent
    backup: 'yes'

- name: Load kernel module
  modprobe: name={{ item }} state=present
  with_items:
    - br_netfilter
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack_ipv4
  ignore_errors: true

- name: Centos ulimits
  template: src=30-limits.conf.j2 dest=/etc/security/limits.d/30-limits.conf

- name: k8s System parameters
  template: src=k8s-sysctl.conf.j2 dest=/etc/sysctl.d/k8s-sysctl.conf

- name: k8s sysctl -p
  shell: "sysctl -p /etc/sysctl.d/k8s-sysctl.conf"
  ignore_errors: true
