# init ENV
- name: Set time zone
  shell: "timedatectl set-timezone Asia/Shanghai"

- name: DNS
  shell: echo "nameserver 114.114.114.114" >> /etc/resolv.conf

- import_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- name: Optimize sshd
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "UseDNS"
    line: "UseDNS no"
  
- name: Optimize sshd
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "GSSAPIAuthentication"
    line: "GSSAPIAuthentication no"
