# Time synchronization
- hosts: all
  roles:
  - { role: chrony, when: "hostvars['NTP_ENABLED'] == 'yes'" }

# 集群节点的公共配置任务
- hosts:
  - kube-master
  - kube-node
  - deploy
  - etcd
  - lb
  roles:
  - init

# [可选]多master部署时的负载均衡配置
- hosts: lb
  roles:
  - lb
