# Time synchronization #
- hosts: all
  roles:
  - { role: chrony, when: "hostvars[groups.deploy[0]]['NTP_ENABLED'] == 'yes'" }

# Create a certificate
- hosts: deploy
  roles:
  - deploy

# Initializing system
- hosts:
  - kube-master
  - kube-node
  - deploy
  - etcd
  - lb
  roles:
  - init

# HA LB master 
- hosts: lb
  roles:
  - lb
