# 国内镜像加速
REG_MIRROR_1: "https://registry.docker-cn.com"
REG_MIRROR_2: "https://docker.mirrors.ustc.edu.cn"

# docker日志相关
LOG_DRIVER: "json-file"
LOG_LEVEL: "warn"
LOG_MAX_SIZE: "10m"
LOG_MAX_FILE: 3

# docker容器存储目录
STORAGE_DIR: "/var/lib/docker"

# harbor私有地址
HARBOR: "hostvars[groups.harbor[0]]"

# docker-ce version
DOCKER_VERSION: "docker-ce-17.03.3.ce"
DOCKER_SE_VERSION: "docker-ce-selinux-17.03.3.ce"
