# --------------yum install docker-ce -----------
- name: remove old docker
  yum: name={{ item }} state=absent
  with_items:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate 
  - docker-logrotate
  - docker-selinux
  - docker-engine-selinux
  - docker-engine

- name: install prepare
  shell: yum install -y yum-utils device-mapper-persistent-data lvm2

- name: yum-config-manager
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: yum install docker-ce
  shell: "yum install -y --setopt=obsoletes=0 {{ DOCKER_VERSION }} {{ DOCKER_SE_VERSION }}"

- name: docker国内镜像加速
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json

- name: 创建docker的systemd unit文件
  template: src=docker.service.j2 dest=/lib/systemd/system/docker.service
  backup: yes
  tags: upgrade_docker, download_docker

- name: 开机启用docker 服务
  shell: systemctl enable docker
  ignore_errors: true

- name: 开启docker 服务
  shell: systemctl daemon-reload && systemctl restart docker
  tags: upgrade_docker


